### PR TITLE
Fix: Dark mode visual inconsistencies across Test Runs and Single Test Run pages

### LINKED ISSUE #2283: Web UI: Support Light/Dark mode
# Story As a galasa web UI user, I want to see the UI content in different themes.

# Background

In settings panel we need this: 

```
Color Theme
===========
o Light mode
o Dark mode 
o Light or dark to match my browser preferences
o Light or dark to match my desktop preference
```

With a radio button. 

There is an IBM Carbon theme tag/component which can pass down the theme to the child components. We can use that?

Can this (please) be stored in browser local storage ?

# Tasks
- [x] Needs hiding behind a feature-flag initially "Control color theme". 
- [x] If the feature flag is turned off, revert to the light mode we use today in all our panels.
- [x] Settings page needs a toggle button with the available options
- [x] All panels need re-working to support a theme control to control the fonts and colour palettes.

### LINKED ISSUE #2323: Inconsistent dark mode styles across UI components
## Describe the bug
There are several visual inconsistencies between light and dark modes.

## Spotted Issues
1. **Test Runs Page→ Table Design Tab**
 Hovering over the drag-and-drop icon causes the tooltip to appear beneath other UI elements due to incorrect z-index stacking.

Image

2. **Test Runs Page→ Search Criteria Tab**
When typing into the Requestor field, the dropdown list appears with a white background, even in dark mode, making it inconsistent and hard to read.

3. **Single Test Run Page → Artifacts Tab**
The download icon remains dark in dark mode, making it barely visible. Additionally, it lacks a tooltip on hover.

Image

### PR DESCRIPTION
**Pull request by shivambisen**
### Description:

This PR resolves multiple UI inconsistencies in dark mode:

Closes galasa-dev/projectmanagement#2323
Closes galasa-dev/projectmanagement#2283

- **Table Design Tab**: Fixed tooltip stacking issue for drag-and-drop icon.
- **Search Criteria Tab**: Corrected white background in Requestor dropdown.
- **Artifacts Tab**: Updated download icon color .

### Changes:
- Adjusted  `overflow`, properties for tooltip visibility.
- Made cahnges in CSS for consistent dark mode styling.

### CODE REVIEW

File: galasa-ui/src/components/test-runs/ArtifactsTab.tsx [hunk 1]
```diff
@@ -337,14 +338,16 @@ export function ArtifactsTab({ artifacts, runId, runName }: { artifacts: Artifac
...
+                      <Tooltip label={translations("download_button")} align="bottom">
+                        <button
+                          type="button"
+                          onClick={handleDownloadClick}
+                          role='download-button'
+                          className={styles.downloadButton}
+                        >
+                          <CloudDownload size={22} className={styles.clouddownload} />
+                        </button>
+                      </Tooltip>
```
Comment (eamansour) [inline galasa-ui/src/components/test-runs/ArtifactsTab.tsx]: Looking better! However, there's still a bit of inconsistency between the download button on the "Run Log" tab and the "Artifacts" tab. For example, you need to hover over the icon in order for it to act like a button, whereas the "Run Log" tab allows you to hover near the button to download the run log.

Also, the padding on the tooltip is different and is a bit too big, I think it would be better to make this tooltip like the one on the "Run Log" tab.

Can the tooltip also appear above the button instead of below?
Screenshot 2025-07-09 at 10 52 55

File: galasa-ui/src/styles/Selector.module.css [hunk 2]
```diff
@@ -30,7 +30,7 @@
 }
 
 .iconButton {
-  background: none;
+  background:#262626;
```
Comment (eamansour) [inline galasa-ui/src/styles/Selector.module.css:33]: Can we remove the rounding on the theme selector button so that it reacts like all the other buttons on the menu bar?
Screenshot 2025-07-09 at 10 51 06

**Review by eamansour — COMMENTED** [review]
Thanks for opening this PR, just spotted a few improvements that can be made!

**Comment by shivambisen** [comment]
@eamansour  implemented the required changes and fixed another theme inconsistency in the test run skeleton.

File: galasa-ui/src/components/test-runs/ArtifactsTab.tsx [hunk 3]
```diff
@@ -337,14 +339,14 @@ export function ArtifactsTab({ artifacts, runId, runName }: { artifacts: Artifac
                       </p>
                     </div>
                     <div className={styles.toolbarOptions}>
-                      <button
-                        type="button"
+                      <Button
+                        kind="ghost"
+                        renderIcon={CloudDownload}
+                        hasIconOnly
+                        iconDescription={translations("download_button")}
```
Comment (eamansour) [inline galasa-ui/src/components/test-runs/ArtifactsTab.tsx:345]: Minor - instead of just "Download", maybe this could say "Download this artifact" to be a bit more descriptive?

File: galasa-ui/src/components/test-runs/ArtifactsTab.tsx [hunk 4]
```diff
@@ -14,6 +14,8 @@ import { downloadArtifactFromServer } from '@/actions/runsAction';
 import { Tile } from '@carbon/react';
 import { handleDownload } from '@/utils/artifacts';
 import { useTranslations } from 'next-intl';
+import { Tooltip } from '@carbon/react';
```
Comment (eamansour) [inline galasa-ui/src/components/test-runs/ArtifactsTab.tsx]: Tooltip is an unused import now, can this be removed?

File: galasa-ui/src/styles/Artifacts.module.css [hunk 5]
```diff
@@ -50,4 +50,7 @@
   cursor: pointer;
   border: none;
   background-color: transparent;
+}
+.clouddownload{
+  color: var(--cds-text-primary);
```
Comment (eamansour) [inline galasa-ui/src/styles/Artifacts.module.css]: Very minor - can the `clouddownload` CSS class be in camelCase (`cloudDownload`) like the rest of the classes in this file and separated with a blank line between classes, just to maintain consistency?

**Review by eamansour — APPROVED** [review]
Looking good! Spotted a few minor improvements but happy to approve assuming they'll be addressed. Thanks for making these changes!

File: galasa-ui/src/styles/Artifacts.module.css (hunk 5 above)
Comment (shivambisen) [reply galasa-ui/src/styles/Artifacts.module.css]: we are no longer using that class so we can remove this
